version: '3.8'

services:
  db:
    image: postgres:15
    container_name: primacy_postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: lucas
      POSTGRES_PASSWORD: devpass
      POSTGRES_DB: primacy
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
